njpp_eat/eat_apply/urls.py
from django.conf.urls import url
from . import views, forms

app_name = 'eat_apply'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^wizard/$',views.ApplicationWizard.as_view([forms.ApplicationFormFilerInfo, forms.ApplicationFormPathSelection, forms.application_short_path_formset]))
]

njpp_eat/njpp_eat/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^eat_apply/', include('eat_apply.urls', namespace="eat_apply")),
    url(r'^admin/', admin.site.urls),
]

njpp_eat/eat_apply/models.py
from django.db import models

# An Application is a single submission. It is essentially the digital version of the paper form. 
# It has Child and Adult objects representing each child and adult on the application. It also has 
# data fields for the status of the family's participation in a public assistance program,the case number if 
# they participate, and all the information from the contact section of the paper form. There are also helper
# fields for the total of all child monthly income, the total of all adult monthly income, and the total 
# adult monthly income broken out by source. These will be 0 if no income information needed to be provided
class Application(models.Model):
    contact_address_one = models.CharField(max_length=200, blank=True)
    contact_address_two = models.CharField(max_length=200, blank=True)
    contact_city = models.CharField(max_length=50, blank=True) # as far as I can find no US city has name longer than 24 chars
    contact_state = models.CharField(max_length=2, blank=True)
    contact_zip = models.CharField(max_length=10, blank=True)
    contact_phone = models.CharField(max_length=10)
    contact_email = models.EmailField(blank=True)
    contact_name_of_filer = models.CharField(max_length=200)
    date_completed = models.DateTimeField()
    participate_assistance = models.BooleanField()
    assistance_case_number = models.CharField(max_length=50, blank=True) # i really hope this is long enough, otherwise ouch

    # NOTE: all income should be converted to monthly before being stored. All income values are monthly income.
    total_child_income = models.IntegerField(blank=True,null=True)
    total_adult_income = models.IntegerField(blank=True,null=True)
    total_adult_income_wages = models.IntegerField(blank=True,null=True)
    total_adult_income_assistance = models.IntegerField(blank=True,null=True)
    total_adult_income_other = models.IntegerField(blank=True,null=True)

    # this is a helper to make it easier to mess with the data in the console
    def __str__(self):
    	return self.contact_name_of_filer

# A Child is one child inside an Application. There will be at least one in every Application. Each Child has a 
# reference to it's Application, the child's name, the child's status as a student, foster child, & homeless/runaway/migrant
# as well as the child's monthly income broken down by source if income information was required to be submitted. 
class Child(models.Model):
	application = models.ForeignKey(Application)
	first_name = models.CharField(max_length=200)
	last_name = models.CharField(max_length=200)
	middle_initial = models.CharField(max_length=1,blank=True)
	student = models.BooleanField()
	foster_child = models.BooleanField()
	homless = models.BooleanField()

	# NOTE: all income should be converted to monthly before being stored. All income values are monthly income.
	total_income = models.IntegerField(blank=True,null=True)
	work_income = models.IntegerField(blank=True,null=True)
	assitance_income = models.IntegerField(blank=True,null=True)
	other_income = models.IntegerField(blank=True,null=True) # Is this enough? Or shoudl it be outside_income && other_income?

	# this is a helper to make it easier to mess with the data in the console
	def __str__(self):
		return self.first_name + " " + self.last_name




# An Adult is one adult inside an Application. There may not be any Adult objects in an Application. There is no
# connection in the system between an Adult and the contact_name_of_filer. An Adult has a reference to it's Application
# the adult's name, the adult's income total and broken down by source, and possibly a SSN.
class Adult(models.Model):
	application = models.ForeignKey(Application)
	first_name = models.CharField(max_length=200)
	last_name = models.CharField(max_length=200)

	# NOTE: all income should be converted to monthly before being stored. All income values are monthly income.
	total_income = models.IntegerField(blank=True,null=True)
	work_income = models.IntegerField(blank=True,null=True)
	assitance_income = models.IntegerField(blank=True,null=True)
	other_income = models.IntegerField(blank=True,null=True)

	# this is a helper to make it easier to mess with the data in the console
	def __str__(self):
		return self.first_name + " " + self.last_name

njpp_eat/eat_apply/forms.py
from django import forms
from django.forms import formset_factory
from django.forms.extras import widgets

from .models import Application, Child, Adult

# This is the form that collects all the information about a given filer. This is Step 4 on the paper form.
class ApplicationFormFilerInfo(forms.Form):
    contact_name_of_filer = forms.CharField(label="Your Full Name", max_length=200)
    no_address = forms.BooleanField(label="I do not have a permanent address", required=False)
    contact_address_one = forms.CharField(label="Street address", max_length=200, required=False)
    contact_address_two = forms.CharField(label="Apartment Number, Suite, etc.", max_length=200, required=False)
    contact_city = forms.CharField(label="City", max_length=50, required=False) # as far as I can find no US city has name longer than 24 chars
    contact_state = forms.CharField(label="State (two characters)", max_length=2, required=False)
    contact_zip = forms.CharField(label="Zip code",max_length=10, required=False)
    contact_phone = forms.CharField(max_length=10, required=False)
    contact_email = forms.EmailField(required=False)
    contact_signature = forms.CharField(label="Please enter your full name below to sign.")

# This is the form that collects the information we're using to route people through the fork in the logic. If the answer is yes to either of these
# questions than the route is the "short path." foster_children is initially hidden and only shown if participate_assistance == True. 
class ApplicationFormPathSelection(forms.Form):
	assitance_choices = ((False, 'No'),(True, 'Yes'))
	foster_choices = ((False, 'No'),(True, 'Yes'))
	participate_assistance = forms.BooleanField(label="Are any members of your household participants in one or more of the following assistance programs: SNAP, TANF, or FDPIR?", widget=forms.RadioSelect(choices=assitance_choices, attrs={'class=': 'form_field radio_field'}))
	foster_children = forms.BooleanField(label="Are ALL of the children you are applying for foster children?", widget=forms.RadioSelect(choices=foster_choices, attrs={'class=': 'form_field radio_field'}))
    
# This is the form to create a Child object in the short path. It doesn't collect any income information because none is required on that path
class ChildNoIncomeForm(forms.Form):
    student_choices = ((False, 'No'), (True, 'Yes'))
    foster_choices = ((False, 'No'), (True, 'Yes'))
    homeless_choices = ((False, 'No'), (True, 'Yes'))

    child_first_name = forms.CharField(label="First Name", max_length=100)
    child_middle_initial = forms.CharField(label="Middle Initial", max_length=1, required=False)
    child_last_name = forms.CharField(label="Last Name", max_length=100)
    child_student = forms.BooleanField(label="Is this child a student?", widget=forms.RadioSelect(choices=student_choices))
    child_foster = forms.BooleanField(label="Is this child a foster child?", widget=forms.RadioSelect(choices=foster_choices))
    child_homeless = forms.BooleanField(label="Is this child homeless, a migrant, or a runaway?", widget=forms.RadioSelect(choices=homeless_choices))

application_short_path_formset = formset_factory(ChildNoIncomeForm)

njpp_eat/eat_apply/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.forms import widgets
from django.forms.models import inlineformset_factory
from django.utils import timezone
from formtools.wizard.views import SessionWizardView

from .models import Application, Child, Adult
from . import forms

# Create your views here.
class IndexView(generic.FormView):
	template_name = "eat_apply/index.html"
	form_class = forms.ApplicationFormFilerInfo


class ApplicationWizard(SessionWizardView):
	template_name = "eat_apply/wizard.html"
	
	def done(self, form_list, **kwargs):
		return render_to_response('eat_apply/done.html',{
			'form-data': [form.cleaned_data for form in form-list],
			})

njpp_eat/eat_apply/templates/eat_apply/base.html
<!DOCTYPE html>
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- force mobile safari to use the width of the device as the width of the viewport and disable initial scale -->
		<meta name="viewport" content="width=device-width; initial-scale=1.0"> 
		<title>NJPP Prototype Application for Free and Reduced Price School Meals</title>
		<link href="{% static 'eat_apply/imgs/favicon.png' %}" type="image/png" rel="icon" />
		<link href="{% static 'eat_apply/css/screen.css' %}" media="screen" rel="stylesheet" type="text/css" />
		<!-- Google fonts for Source Serif Pro face-->
		<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,700' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<header>
			<h1 id="form-title">2016-2017 Application for Free and Reduced Price School Meals</h1>
		</header>
		<div id="form-content">
			{% block content %} something went wrong, try reloading and if that doesn't work contact support. {% endblock %}
		</div>
		<div id="district-contact-area">
			<h2>Have questions?</h2>
			<p>
				Contact <em>NJPP Unified School District</em> and someone will be happy to answer your questions
			</p>
			<p>
				<span class="contact-label">by phone:</span> 555.555.5555
			</p>
			<p>
				<span class="contact-label">by email:</span> <a href="mailto:#">eat-help@njppunified.edu</a>
			</p>
		</div>
		<script src="http://code.jquery.com/jquery-1.12.0.min.js"></script>
		<script src="{%static 'eat_apply/js/jquery.formset.js' %}"></script>
		<script type="text/javascript">
    		$(function() {
        		$('tbody').formset();
    		})
		</script>
	</body>
</html>

njpp_eat/eat_apply/templates/eat_apply/index.html
{% extends "eat_apply/base.html" %}
{% block content %}
		<p>
			This is an application for free and reduced-price school meals. You only need to fill out one application per household, even if your children attend multiple schools in the same district. Applications must be filled out by an adult member (over 18) of the household.
		</p>
		<p>
			Please enter the information for the adult filling out the application below. If a permanent street address is not available, sharing a phone number or email address (both optional) helps us contact you.
		</p>
		{% if error_message %}<div class="error">{{error_message}}</div>{% endif %}
		<div class="filer_info_form">
			<form action="{% url 'eat_apply:index' %}" method="get">
				{{form}}
			</form>
		</div>


{% endblock %}

njpp_eat/eat_apply/templates/eat_apply/wizard.html
{% extends "eat_apply/base.html" %}
{% block content %}
		{% if error_message %}<div class="error">{{error_message}}</div>{% endif %}
		<div class="filer_info_form">
			<form action="" method="post">{% csrf_token %}
		<p>Step {{wizard.steps.step1}} of {{wizard.steps.count}}</p>
		<table>
			{{wizard.management_form}}
			{% if wizard.form.forms %}
				{{wizard.form.management_form}}
				{% for form in wizard.form.forms %}
					{{form}}
				{% endfor %}
			{% else %}
				{{wizard.form}}
			{% endif %}
		</table>
		{% if wizard.steps.prev %}
			<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">first step</button>
			<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">prev step</button>
		{% endif %}
		<input type="submit" value="submit"/>
		</form>
		</div>
{% endblock %}